CREATE TABLE `User` (
	`Uid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) UNIQUE,
	`email` VARCHAR(255) UNIQUE,
	`Phone Number` VARCHAR(255) UNIQUE,
	`Address` VARCHAR(255),
	PRIMARY KEY(`Uid`)
);

CREATE TABLE `Order` (
	`Oid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Uid` INT UNIQUE,
	`Total_Price` FLOAT,
	PRIMARY KEY(`Oid`)
);

CREATE TABLE `Order Product` (
	`OPid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Oid` INT UNIQUE,
	`Pid` INT UNIQUE,
	`Quantity` INT,
	`Price` FLOAT,
	`Sid` INT UNIQUE,
	PRIMARY KEY(`OPid`)
);

CREATE TABLE `Supplier` (
	`Sid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Company/Store Name` VARCHAR(255),
	`Address` VARCHAR(255),
	`Contact Number` VARCHAR(255),
	`PAN Number` VARCHAR(255),
	PRIMARY KEY(`Sid`)
);

CREATE TABLE `Product` (
	`Pid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255),
	`Price` FLOAT,
	`Rating` INT,
	PRIMARY KEY(`Pid`)
);

CREATE TABLE `Appointment` (
	`Aid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Uid` INT UNIQUE,
	`PRid` INT UNIQUE,
	PRIMARY KEY(`Aid`)
);

CREATE TABLE `Professionals` (
	`PRid` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) UNIQUE,
	`Role` VARCHAR(255),
	`Qualification` VARCHAR(255),
	`Experience` INT,
	`Operating Area` VARCHAR(255),
	`Phone Number` VARCHAR(255),
	PRIMARY KEY(`PRid`)
);

ALTER TABLE `Order`
ADD FOREIGN KEY(`Uid`) REFERENCES `User`(`Uid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Order Product`
ADD FOREIGN KEY(`Oid`) REFERENCES `Order`(`Oid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Supplier`
ADD FOREIGN KEY(`Sid`) REFERENCES `Order Product`(`Sid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Product`
ADD FOREIGN KEY(`Pid`) REFERENCES `Order Product`(`Pid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Professionals`
ADD FOREIGN KEY(`PRid`) REFERENCES `Appointment`(`PRid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Appointment`
ADD FOREIGN KEY(`Uid`) REFERENCES `User`(`Uid`)
ON UPDATE NO ACTION ON DELETE NO ACTION;